{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import rev\n",
    "# load a chart\n",
    "chart = rev.Chart('examples/vega1.png', text_from=0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# training text role classifier\n",
    "import pandas as pd\n",
    "import rev.text\n",
    "data = pd.read_csv('data/features_all.csv')\n",
    "features = data[rev.text.classifier.VALID_COLUMNS]\n",
    "types = data['type']\n",
    "\n",
    "text_clf = rev.text.TextClassifier()\n",
    "text_clf.train(features, types)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "models/mark_classifier/charts5cats/deploy.prototxt\n",
      "models/mark_classifier/charts5cats/snapshots/model_iter_50000.caffemodel\n",
      "models/mark_classifier/charts5cats/ilsvrc_2012_mean.npy\n",
      "['bar']\n"
     ]
    }
   ],
   "source": [
    "##########################################################################################\n",
    "# mark type classifier\n",
    "import rev.mark\n",
    "mark_clf = rev.mark.MarkClassifier()\n",
    "print (mark_clf.classify([chart]))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "##########################################################################################\n",
    "#feature extraction (single)\n",
    "import rev.text\n",
    "text_features = rev.text.feature_extractor.from_chart(chart)\n",
    "print (text_features)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "##########################################################################################\n",
    "# text role classification\n",
    "import rev\n",
    "# load a chart\n",
    "chart = rev.Chart('examples/vega1.png', text_from=0)\n",
    "import rev.text\n",
    "text_clf = rev.text.TextClassifier('default')\n",
    "text_type_preds = text_clf.classify(chart)\n",
    "print (text_type_preds)\n",
    "##########################################################################################"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# training text role classifier\n",
    "import rev.text\n",
    "import pandas as pd\n",
    "data = pd.read_csv('data/features_all.csv')\n",
    "features = data[rev.text.classifier.VALID_COLUMNS]\n",
    "types = data['type']\n",
    "\n",
    "text_clf = rev.text.TextClassifier()\n",
    "text_clf.train(features, types)\n",
    "text_clf.save_model('models/new_text_role_classifier/text_type_classifier.pkl')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import rev\n",
    "from rev.text.localizer import TextLocalizer\n",
    "\n",
    "\n",
    "# load a chart\n",
    "chart = rev.Chart('examples/vega1.png', text_from=0)\n",
    "\n",
    "#todo:\n",
    "localizer = TextLocalizer(method = 'default')\n",
    "\n",
    "text_boxes = localizer.localize(chart, method='default', debug = False)\n",
    "\n",
    "new_chart = chart.copy(text_from=2)\n",
    "new_chart.text_boxes = text_boxes\n",
    "\n",
    "new_chart.save_text_boxes()\n",
    "new_chart.save_debug_image()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa35ff5df60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa35ff5df60>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa35ff5df60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa35ff5df60>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa35ff5dcf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa35ff5dcf8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa35ff5dcf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa35ff5dcf8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7fa364628a58>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7fa364628a58>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7fa364628a58>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7fa364628a58>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa35ff5d1d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa35ff5d1d0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa35ff5d1d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa35ff5d1d0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa3645ac748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa3645ac748>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa3645ac748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa3645ac748>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7fa2e92505c0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7fa2e92505c0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7fa2e92505c0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7fa2e92505c0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa35ff5df60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa35ff5df60>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa35ff5df60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa35ff5df60>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e95fa9b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e95fa9b0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e95fa9b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e95fa9b0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e97c8b38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e97c8b38>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e97c8b38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e97c8b38>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7fa2e828c7f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7fa2e828c7f0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7fa2e828c7f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7fa2e828c7f0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa3641910b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa3641910b8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa3641910b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa3641910b8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e90d7ba8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e90d7ba8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e90d7ba8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e90d7ba8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364628be0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364628be0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364628be0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364628be0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7fa2e95fa9b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7fa2e95fa9b0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7fa2e95fa9b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7fa2e95fa9b0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e80b1f60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e80b1f60>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e80b1f60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e80b1f60>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e80b12e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e80b12e8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e80b12e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e80b12e8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364608ac8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364608ac8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364608ac8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364608ac8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7fa2e96dacc0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7fa2e96dacc0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7fa2e96dacc0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7fa2e96dacc0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e86f4240>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e86f4240>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e86f4240>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e86f4240>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa3645ac748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa3645ac748>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa3645ac748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa3645ac748>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e80b1160>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e80b1160>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e80b1160>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e80b1160>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa3644f25c0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa3644f25c0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa3644f25c0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa3644f25c0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e862fda0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e862fda0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e862fda0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e862fda0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364297e80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364297e80>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364297e80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364297e80>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e82ba5f8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e82ba5f8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e82ba5f8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa2e82ba5f8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364319780>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364319780>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364319780>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364319780>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364319780>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364319780>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364319780>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364319780>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364319780>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364319780>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364319780>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa364319780>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "INFO:tensorflow:Restoring parameters from /home/joao/Documents/repos/rev/rev/text/../../models/pixel_link_text_detection/model.ckpt-46231\n",
      "max 319\n",
      "joao 20.0 20.0 21.0\n",
      "joao 22.999996185302734 61.99999237060547 22.999996185302734\n",
      "joao 2.0 19.0 2.0\n",
      "joao 24.0 24.0 106.0\n",
      "joao 27.999996185302734 27.999996185302734 111.99998474121094\n",
      "joao 1.0 1.0 3.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 1.0 1.0 8.0\n",
      "joao 24.0 24.0 50.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 15.0\n",
      "joao 0.0 3.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 22.0 22.0 109.0\n",
      "joao 2.0 4.0 2.0\n",
      "joao 13.0 13.0 27.0\n",
      "joao 0.0 3.0 0.0\n",
      "joao 1.0 1.0 3.0\n",
      "joao 8.0 8.0 11.0\n",
      "joao 2.0 2.0 8.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 3.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 20.0 20.0 21.0\n",
      "joao 1.0 1.0 9.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 0.0 21.0 0.0\n",
      "joao 0.0 3.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 24.999996185302734 24.999996185302734 108.99998474121094\n",
      "joao 1.0 1.0 2.0\n",
      "joao 3.0 22.0 3.0\n",
      "joao 21.0 22.0 21.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 2.0 3.0 2.0\n",
      "joao 2.0 3.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 2.0 6.0 2.0\n",
      "joao 1.0 1.0 3.0\n",
      "joao 0.0 3.0 0.0\n",
      "joao 1.0 1.0 5.0\n",
      "joao 1.0 1.0 8.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 0.0 6.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 25.0 81.0 25.0\n",
      "joao 0.0 3.0 0.0\n",
      "joao 1.0 1.0 3.0\n",
      "joao 8.0 9.0 8.0\n",
      "joao 0.0 3.0 0.0\n",
      "joao 2.0 2.0 3.0\n",
      "joao 2.0 7.0 2.0\n",
      "joao 21.0 21.0 24.0\n",
      "joao 47.00221252441406 95.09548950195312 47.00221252441406\n",
      "joao 55.0 55.0 58.0\n",
      "joao 42.61232376098633 144.13888549804688 42.61232376098633\n",
      "joao 48.08325958251953 107.48021697998047 48.08325958251953\n",
      "joao 37.85099792480469 75.62251281738281 37.85099792480469\n",
      "joao 49.96537780761719 107.94640350341797 49.96537780761719\n",
      "joao 42.42640686035156 128.69342041015625 42.42640686035156\n",
      "joao 2.0 9.0 2.0\n",
      "joao 1.0 1.0 3.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 3.0 0.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 3.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 3.0 0.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 3.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 3.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 3.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 3.0\n",
      "joao 49.0592155456543 112.99559020996094 49.0592155456543\n",
      "joao 1.0 1.0 2.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 2.0 4.0 2.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 3.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 3.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 3.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 3.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 2.0 2.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 2.0 7.0 2.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 3.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 3.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 3.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 3.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 3.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 3.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 3.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 3.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 3.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 3.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 3.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 3.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 3.0 5.0 3.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 1.0 1.0 2.0\n",
      "joao 0.0 2.0 0.0\n",
      "joao 0.0 3.0 0.0\n",
      "joao 1.0 1.0 3.0\n",
      "joao 0.0 3.0 0.0\n"
     ]
    }
   ],
   "source": [
    "import rev\n",
    "from rev.text.localizer import TextLocalizer\n",
    "\n",
    "# load a chart\n",
    "chart = rev.Chart('examples/pmc1.png', text_from=0)\n",
    "localizer = TextLocalizer()\n",
    "text_boxes = localizer.localize(chart, method='pixel_link', debug=False)\n",
    "new_chart = chart.copy(text_from=2)\n",
    "new_chart.text_boxes = text_boxes\n",
    "new_chart.save_text_boxes()\n",
    "new_chart.save_debug_image()\n",
    "\n",
    "\n",
    "from rev.spec import SpecGenerator\n",
    "spec_gen = SpecGenerator()\n",
    "spec = spec_gen.generate(chart)\n",
    "print(spec)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
